process.on('uncaughtException', (error) => {
    if (error instanceof Error && error.name === 'ExitPromptError') {
        console.log('ðŸ‘‹ until next time!')
    } else {
        // Rethrow unknown errors
        throw error
    }
})
